name: x_pictures
description: >
  Starter app

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+23

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any
  intl: any

  # Stream
  # stream_transform: ^2.1.0
  rxdart: ^0.28.0

  # -- service locator -- #
  provider: ^6.1.2

  # -- state manager -- #
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

  # -- codegen -- #
  json_annotation: ^4.9.0
  # freezed_annotation: ^2.4.1

  # -- networking -- #
  dio: ^5.3.3

  # Persisting
  # drift: ^2.13.1
  # sqlite3: ^2.3.0
  shared_preferences: ^2.2.2
  # sqlite3_flutter_libs: ^0.5.18

  # Logging
  stack_trace: ^1.11.0
  sentry_flutter: ^8.9.0
  logging: ^1.2.0

  # Utils
  # pure: ^0.2.0
  device_preview: ^1.2.0

  convert: ^3.0.1
  platform_info: ^5.0.0
  path: ^1.8.3
  path_provider: ^2.1.0
  mocktail: ^1.0.1
  reactive_forms: ^17.0.1
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  svg_flutter: ^0.0.1
  network_info_plus: ^6.0.1
  flutter_secure_storage: ^9.2.2
  share_plus: ^10.0.2

  # -- navigation -- #
  go_router: ^14.2.7

  # -- localization -- #
  flutter_localizations:
    sdk: flutter
  slang: ^3.25.0
  slang_flutter: ^3.25.0

  # -- ui -- #
  loading_animation_widget: ^1.2.1
  flex_color_scheme: ^7.3.1
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6
  persistent_bottom_nav_bar: any
  pinput: ^5.0.0
  auto_size_text: ^3.0.0
  gap: ^3.0.1
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  settings_ui: ^2.0.2
  flutter_slidable: ^3.1.0
  # pro_image_editor: ^4.2.5
  percent_indicator: ^4.2.3
  grouped_list: ^6.0.0
  grouped_grid: ^0.1.2
  modal_bottom_sheet: ^3.0.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3

  animated_toggle_switch: ^0.8.3

dev_dependencies:
  # -- testing -- #
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # -- utils -- #
  flutter_gen_runner: ^5.3.2
  flutter_native_splash: ^2.3.5

  # -- codegen -- #
  build_runner: ^2.4.6
  mobx_codegen: ^2.6.0+1
  json_serializable: ^6.7.1
  slang_build_runner: ^3.25.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/photos/
    - assets/icons/
    - assets/docs/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf

flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 80

icons_launcher:
  image_path: "assets/icon.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true
