# Generated by Django 3.2.22 on 2024-07-11 15:05

import core.common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Face2ImgJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Process'), (2, 'Success'), (-1, 'Error')], default=0, verbose_name='Status')),
                ('estimated_time', models.IntegerField(default=60, help_text='In second', verbose_name='Estimated time')),
                ('time_spent', models.IntegerField(default=0, help_text='In seconds', verbose_name='Time spent')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Cost')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Face2Img Job',
                'verbose_name_plural': 'Face2Img Jobs',
            },
        ),
        migrations.CreateModel(
            name='Lora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('lora_name', models.CharField(max_length=255, verbose_name='Lora name')),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Process'), (2, 'Success'), (-1, 'Error')], default=0, verbose_name='Status')),
                ('estimated_time', models.IntegerField(default=60, help_text='In second', verbose_name='Estimated time')),
                ('training_time_seconds', models.IntegerField(blank=True, null=True, verbose_name='Training time')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Cost')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loras', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Lora',
                'verbose_name_plural': 'User Loras',
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sd_model', models.CharField(max_length=255, verbose_name='SD model')),
                ('positive_prompt', models.CharField(max_length=255, verbose_name='Prompt')),
                ('negative_prompt', models.CharField(max_length=255, verbose_name='Negative prompt')),
                ('image_default_height', models.IntegerField(default=768, verbose_name='Height')),
                ('image_default_width', models.IntegerField(default=512, verbose_name='Height')),
                ('steps', models.IntegerField(default=20, verbose_name='Steps')),
                ('batch_size', models.IntegerField(default=4, verbose_name='Batch size')),
                ('sampler_name', models.CharField(max_length=255, verbose_name='Sampler name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Pack',
                'verbose_name_plural': 'Packs',
            },
        ),
        migrations.CreateModel(
            name='PackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.common.utils.PathAndRename('face2img_packs_default_images/'), verbose_name='Image')),
                ('sort', models.IntegerField(default=0, verbose_name='Sort')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='face2img.pack', verbose_name='Pack')),
            ],
            options={
                'verbose_name': 'Pack Image',
                'verbose_name_plural': 'Pack Images',
            },
        ),
        migrations.CreateModel(
            name='LoraTrainingFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.common.utils.PathAndRename('face2img_lora_training_faces/'), verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('lora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_faces', to='face2img.lora', verbose_name='Lora')),
            ],
            options={
                'verbose_name': 'Lora Training Face',
                'verbose_name_plural': 'Lora Training Faces',
            },
        ),
        migrations.CreateModel(
            name='Face2ImgJobResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.common.utils.PathAndRename('face2img/job_results/'), verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='face2img.face2imgjob', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Job Result',
                'verbose_name_plural': 'Job Results',
            },
        ),
        migrations.AddField(
            model_name='face2imgjob',
            name='lora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='face2img.lora', verbose_name='Lora'),
        ),
        migrations.AddField(
            model_name='face2imgjob',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='face2img.pack', verbose_name='Pack'),
        ),
        migrations.AddField(
            model_name='face2imgjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face2img_jobs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
