# Generated by Django 3.2.22 on 2024-07-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face2img', '0002_lora_train_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lora',
            name='train_model_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Train model name'),
        ),
    ]
