# Generated by Django 3.2.22 on 2024-07-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face2img', '0003_lora_train_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='category',
            field=models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Hair style', 'Hair style'), ('Smart tool', 'Smart tool')], default='Smart tool', max_length=255, verbose_name='Category'),
        ),
    ]
