# Generated by Django 3.2.22 on 2023-12-26 14:59

import core.common.mixins
import core.common.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('public_title', models.CharField(max_length=255, verbose_name='Public title')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('public_description', models.TextField(default='', verbose_name='Public description')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=core.common.utils.PathAndRename('products/'), verbose_name='Image')),
                ('type', models.CharField(choices=[('subscription', 'Subscription'), ('one-time', 'One time')], default='subscription', max_length=255, verbose_name='Type')),
                ('lifetime', models.IntegerField(blank=True, default=None, help_text='In second', null=True, verbose_name='Lifetime')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Amount')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
            bases=(core.common.mixins.ImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('rub', 'RUB')], max_length=255, verbose_name='Currency')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Amount')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shop.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('product', 'currency'), name='unique_price'),
        ),
    ]
