# Generated by Django 3.2.22 on 2023-12-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_paymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='sub_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Sub ID'),
        ),
    ]
