# Generated by Django 4.2.5 on 2024-01-08 14:55
from django.db import migrations


def update_advance(cls_product, cls_price):
    month = cls_product.objects.get(pk=1)
    month.paypal_product_id = 'Product-1-0-XPICT'
    month.stripe_product_id = 'prod_PKhUmefiJ5kTjd'
    month.save()

    price_month = cls_price.objects.get(pk=1)
    price_month.paypal_billing_plan_id = 'P-7XM97035T8685331YMWL7CQQ'
    price_month.stripe_price_id = 'price_1OW25iDijmhB69Umix3LdvsL'
    price_month.save()

    week = cls_product.objects.get(pk=2)
    week.paypal_product_id = 'Product-2-0-XPICT'
    week.stripe_product_id = 'prod_PKhjylg8ZZcZwR'
    week.save()

    price_week = cls_price.objects.get(pk=2)
    price_week.paypal_billing_plan_id = 'P-2PA72654GE2711608MWN4IGY'
    price_week.stripe_price_id = 'price_1OW2JcDijmhB69UmzwwwIwJq'
    price_week.save()


def update_premium(cls_product, cls_price):
    month = cls_product.objects.get(pk=3)
    month.paypal_product_id = 'Product-3-0-XPICT'
    month.stripe_product_id = 'prod_PKhrr5eJfxoIzC'
    month.save()

    price_month = cls_price.objects.get(pk=3)
    price_month.paypal_billing_plan_id = 'P-34L125305N328910KMVO77SY'
    price_month.stripe_price_id = 'price_1OW2RXDijmhB69UmTfQWw4ba'
    price_month.save()

    week = cls_product.objects.get(pk=4)
    week.paypal_product_id = 'Product-5-0-XPICT'
    week.stripe_product_id = 'prod_PKhs4JQsXDMF0l'
    week.save()

    price_week = cls_price.objects.get(pk=4)
    price_week.paypal_billing_plan_id = 'P-2J64595177553802SMWN4JLI'
    price_week.stripe_price_id = 'price_1OW2SwDijmhB69UmJpCXBrRE'
    price_week.save()

    year = cls_product.objects.get(pk=5)
    year.paypal_product_id = 'Product-4-0-XPICT'
    year.stripe_product_id = 'prod_PKht4p5opFYQBF'
    year.save()

    price_year = cls_price.objects.get(pk=5)
    price_year.paypal_billing_plan_id = 'P-9SK84495DC4552244MVPAASY'
    price_year.stripe_price_id = 'price_1OW2U8DijmhB69UmWlyYxkUe'
    price_year.save()


def forwards_func(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    Price = apps.get_model('shop', 'Price')

    update_advance(cls_product=Product, cls_price=Price)
    update_premium(cls_product=Product, cls_price=Price)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0006_auto_20240107_2242'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
