# Generated by Django 3.2.22 on 2024-01-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_add_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='invoice_id',
            field=models.CharField(max_length=500, unique=True, verbose_name='Invoice ID'),
        ),
    ]
