# Generated by Django 3.2.22 on 2024-01-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_paymentorder_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='payment_url',
            field=models.URLField(blank=True, default=None, max_length=500, null=True, verbose_name='Payment url'),
        ),
    ]
