# Generated by Django 4.2.5 on 2024-01-17 14:55

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    Price = apps.get_model('shop', 'Price')

    advance_year = Product.objects.create(
        id=6,
        title='Advance (Year)',
        public_title='Advance',
        type='subscription',
        lifetime=60 * 60 * 24 * 30 * 12,
        amount=2400,

        paypal_product_id='Product-6-0-XPICT',
        stripe_product_id='prod_POFBlN2N8gkWoP',
    )

    Price.objects.bulk_create([
        Price(id=6, currency='usd', price=64.9, product_id=advance_year.id,
              paypal_billing_plan_id='P-971537175E6160341MWTXLKQ',
              stripe_price_id='price_1OZShYDijmhB69UmM5oz3yXS'),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0010_stripecustomer'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
