# Generated by Django 3.2.22 on 2024-01-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_add_advance_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='from_shop',
            field=models.BooleanField(default=False, verbose_name='From shop'),
        ),
    ]
