# Generated by Django 4.2.5 on 2024-01-27

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    Price = apps.get_model('shop', 'Price')

    tokens_pack_10pcs = Product.objects.create(
        id=7,
        title='Tokens pack (10 pcs)',
        public_title='Tokens pack (10 pcs)',
        type='one-time',
        amount=10,
        stripe_product_id='prod_PS7NQHHvksomzE',
    )
    tokens_pack_21pcs = Product.objects.create(
        id=8,
        title='Tokens pack (21 pcs)',
        public_title='Tokens pack (21 pcs)',
        type='one-time',
        amount=21,
        stripe_product_id='prod_PS7Pn8g4yamt0g',
    )
    tokens_pack_32pcs = Product.objects.create(
        id=9,
        title='Tokens pack (32 pcs)',
        public_title='Tokens pack (32 pcs)',
        type='one-time',
        amount=32,
        stripe_product_id='prod_PS7QDAlVkFDHec',
    )
    tokens_pack_60pcs = Product.objects.create(
        id=10,
        title='Tokens pack (60 pcs)',
        public_title='Tokens pack (60 pcs)',
        type='one-time',
        amount=60,
        stripe_product_id='prod_PS7QH6FsB6GRrt',
    )
    tokens_pack_120pcs = Product.objects.create(
        id=11,
        title='Tokens pack (120 pcs)',
        public_title='Tokens pack (120 pcs)',
        type='one-time',
        amount=120,
        stripe_product_id='prod_PS7RvRGKfLoZFG',
    )

    Price.objects.bulk_create([
        Price(id=7, currency='usd', price=4.9, product_id=tokens_pack_10pcs.id,
              stripe_price_id='price_1OdD8hDijmhB69Um6pAdUkEu'),
        Price(id=8, currency='usd', price=9.9, product_id=tokens_pack_21pcs.id,
              stripe_price_id='price_1OdDAhDijmhB69UmcfoTQXPH'),
        Price(id=9, currency='usd', price=14.9, product_id=tokens_pack_32pcs.id,
              stripe_price_id='price_1OdDBYDijmhB69Um6gFX8zsP'),
        Price(id=10, currency='usd', price=24.9, product_id=tokens_pack_60pcs.id,
              stripe_price_id='price_1OdDC7DijmhB69UmNFYNino8'),
        Price(id=11, currency='usd', price=49.9, product_id=tokens_pack_120pcs.id,
              stripe_price_id='price_1OdDCSDijmhB69UmsNkOfa9B'),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0012_paymentorder_from_shop'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
