# Generated by Django 4.2.5 on 2024-02-02

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    Price = apps.get_model('shop', 'Price')

    special_premium_month_subscription = Product.objects.create(
        id=12,
        title='Premium (mouth) (Special offer)',
        public_title='Premium (Special offer)',
        lifetime=2592000,
        amount=151.50,

        paypal_product_id='Product-12-0-XPICT',
        stripe_product_id='',
    )
    special_tokens_pack_32pcs = Product.objects.create(
        id=13,
        title='Tokens pack (32 pcs) (Special offer)',
        public_title='Tokens pack (32 pcs) (Special offer)',
        type='one-time',
        amount=32,
        stripe_product_id='',
    )

    Price.objects.bulk_create([
        Price(id=12, currency='usd', price=14.9, product_id=special_premium_month_subscription.id,
              paypal_billing_plan_id='P-8L921411HJ7628127MW6NERQ',
              stripe_price_id=''),
        Price(id=13, currency='usd', price=9.9, product_id=special_tokens_pack_32pcs.id,
              paypal_billing_plan_id='',
              stripe_price_id=''),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0013_add_one_time_products'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
