# Generated by Django 3.2.22 on 2024-02-07 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0014_add_special_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='is_sent_email',
            field=models.BooleanField(default=False, verbose_name='Sent email'),
        ),
        migrations.CreateModel(
            name='PaymentOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('INFO', 'Info'), ('ERROR', 'Error')], default='INFO', max_length=20, verbose_name='Action')),
                ('text', models.TextField(verbose_name='Text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_logs', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='log', to='shop.paymentorder', verbose_name='Payment Order')),
            ],
            options={
                'verbose_name': 'Payment order log',
                'verbose_name_plural': 'Payment order logs',
                'ordering': ['created', 'id'],
            },
        ),
    ]
