# Generated by Django 4.2.5 on 2024-02-07

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    PaymentOrder = apps.get_model('shop', 'PaymentOrder')
    PaymentOrder.objects.filter(status=1, is_sent_email=False).update(
        is_sent_email=True,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0015_auto_20240207_0752'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
