# Generated by Django 4.2.5 on 2024-02-07

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    PaymentOrder = apps.get_model('shop', 'PaymentOrder')
    PaymentOrderLog = apps.get_model('shop', 'PaymentOrderLog')

    ids = [
        'e97adacd-4b8c-45af-bb75-09910d411eab',
        '0a8d8756-1248-40d4-ada4-732481a56731',
        '6526dc0d-14e4-4ebf-bfbf-9d34866def0d',
        'f694d781-1e1d-4669-a29d-90157691b21e',
        'b077e9c4-e065-4e32-b541-700ccd687c3f',
        'f3e2c75d-0225-441f-99b0-60316fec54c7',
    ]

    # for order in PaymentOrder.objects.filter(pk__in=ids):
    #     PaymentOrderLog.objects.create(
    #         order=order,
    #         action='INFO',
    #         text=(
    #             f'The book has been successfully sent to: {order.user.email}\n'
    #             f'Book name: {order.book_name}'
    #         ),
    #     )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0016_update_sent_email'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
