# Generated by Django 3.2.22 on 2024-03-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_update_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='patreon_product_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Patreon product id'),
        ),
    ]
