# Generated by Django 4.2.5 on 2024-02-19
import decimal

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')

    pack_ids = {
        1: 22518426,
        2: 22518452,
        3: 22312079,
        4: 22518448,
        5: 22518436,
        6: 22518442,
        7: 22518459,
        8: 22518462,
        9: 22518468,
        10: 22518471,
        11: 22518474,
        14: 22518480,
    }

    for product_id, patreon_product_id in pack_ids.items():
        Product.objects.filter(
            pk=product_id,
        ).update(
            patreon_product_id=patreon_product_id,
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('shop', '0021_product_patreon_product_id'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
