# Generated by Django 3.2.22 on 2024-01-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_set_undress_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatejob',
            name='negative_prompt',
            field=models.TextField(default='', verbose_name='Negative prompt'),
        ),
        migrations.AlterField(
            model_name='generatejob',
            name='positive_prompt',
            field=models.TextField(default='', verbose_name='Positive prompt'),
        ),
        migrations.AlterField(
            model_name='undressjob',
            name='negative_prompt',
            field=models.TextField(default='', verbose_name='Negative prompt'),
        ),
        migrations.AlterField(
            model_name='undressjob',
            name='positive_prompt',
            field=models.TextField(default='', verbose_name='Positive prompt'),
        ),
    ]
