# Generated by Django 3.2.22 on 2024-01-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20240107_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='use_many_filters',
            field=models.BooleanField(default=True, verbose_name='Use many filters'),
        ),
    ]
