# Generated by Django 3.2.22 on 2024-01-22

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Category = apps.get_model('jobs', 'Category')

    category_female_undress = Category.objects.get(pk=1)
    category_female_undress.use_many_filters = False
    category_female_undress.save()

    category_male_undress = Category.objects.get(pk=2)
    category_male_undress.use_many_filters = False
    category_male_undress.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0005_category_use_many_filters'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
