# Generated by Django 3.2.22 on 2024-01-22

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    SDModel = apps.get_model('jobs', 'SDModel')

    SDModel.objects.create(
        id=8,
        name='Semi realism (Generate)',
        public_name='Semi realism',
        model_name='realisticAfmix_realisticAfmix_75178.safetensors',
        type=0,
        raw_prompt='a photo of',
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0006_custom'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
