# Generated by Django 3.2.22 on 2024-01-23

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Category = apps.get_model('jobs', 'Category')
    Category.objects.update(use_many_filters=False)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0008_add_new_action'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
