# Generated by Django 3.2.22 on 2024-01-23

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Action = apps.get_model('jobs', 'Action')

    Action.objects.filter(id__in=(47, 48, 49, 50, 51, 52, 53)).update(
        public_name='Pov Reverse Cowgirl',
        raw_prompt1='in reverse (cowgirl pose)',
        raw_prompt2='',
    )

    Action.objects.filter(id__in=(40, 41, 42, 43, 44, 45, 46)).update(
        raw_prompt1='in (cowgirl pose), correct penis, cowGirlV1',
        raw_prompt2='',
    )

    Action.objects.filter(id__in=(33, 34, 35, 36, 37, 38, 39)).update(
        raw_prompt1='with dildo, beautiful face, ((correct face)), dildoVaginaV1',
        raw_prompt2='',
    )

    Action.objects.filter(id__in=(21, 22, 23, 24, 25, 26)).update(
        raw_prompt1='',
        raw_prompt2='((correct Vagina)), (((naked Vagina))), sexy essential pose',
    )

    Action.objects.filter(id__in=(15, 16, 17, 18, 19, 20)).update(
        raw_prompt1='(beautiful ass), spread pussy, perfect penis',
        raw_prompt2='anal photo',
    )

    Action.objects.filter(id__in=(9, 10, 11, 12, 13, 14)).update(
        raw_prompt1='in titjob pose',
        raw_prompt2='correct penis, beautiful tits',
    )

    Action.objects.filter(id__in=(3, 4, 5, 6, 7, 8)).update(
        raw_prompt1='',
        raw_prompt2='pussy juice, spread pussy, ((with cumshot on her body))',
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0009_update_categories'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
