# Generated by Django 3.2.22 on 2024-01-23

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Filter = apps.get_model('jobs', 'Filter')

    Filter.objects.filter(id__in=(236, 237, 238, 240)).update(
        raw_prompt='(correct proportion of face), (beautiful face), face with expression',
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0010_update_name'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
