# Generated by Django 3.2.22 on 2024-01-27 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_update_raw_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyGenerateJob',
            fields=[
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fake_job', serialize=False, to='jobs.generatejob', verbose_name='Generate job')),
            ],
            options={
                'verbose_name': 'Fake job',
                'verbose_name_plural': 'Fake jobs',
            },
        ),
    ]
