# Generated by Django 3.2.22 on 2024-01-24
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_proxygeneratejob'),
    ]

    operations = [
        migrations.RenameModel("ImageHub", "ImageGallery")
    ]
