# Generated by Django 3.2.22 on 2024-01-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_rename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name': 'Image Gallery', 'verbose_name_plural': 'Image Gallery'},
        ),
        migrations.RenameField(
            model_name='imagegallery',
            old_name='generate_job',
            new_name='job',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='created',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='updated',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
