# Generated by Django 3.2.22 on 2024-01-29

from django.db import migrations


def forwards_func(apps, schema_editor):
    Action = apps.get_model('jobs', 'Action')

    Action.objects.bulk_create([
        Action(
            id=54, name='Default (Cartoon Generate)',
            public_name='Default', type=0, sd_model_id=3,
            lora_name='', raw_prompt1='',
        ),
        Action(
            id=55, name='Default (Anime Generate)',
            public_name='Default', type=0, sd_model_id=4,
            lora_name='', raw_prompt1='',
        ),
        Action(
            id=56, name='Default (Furry Generate)',
            public_name='Default', type=0, sd_model_id=5,
            lora_name='', raw_prompt1='',
        ),
        Action(
            id=57, name='Default (3D Generate)',
            public_name='Default', type=0, sd_model_id=6,
            lora_name='', raw_prompt1='',
        ),
        Action(
            id=58, name='Default (Art Generate)',
            public_name='Default', type=0, sd_model_id=7,
            lora_name='', raw_prompt1='',
        ),
        Action(
            id=59, name='Default (Semi realism Generate)',
            public_name='Default', type=0, sd_model_id=8,
            lora_name='', raw_prompt1='',
        ),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20240124_1851'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
