# Generated by Django 3.2.22 on 2024-02-01 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20240129_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackUndressJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='User ID')),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Process'), (2, 'Partially Success'), (3, 'Success'), (-1, 'Error')], default=0, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('jobs', models.ManyToManyField(related_name='pack', to='jobs.UndressJob', verbose_name='Jobs')),
            ],
            options={
                'verbose_name': 'Pack Undress job',
                'verbose_name_plural': 'Pack Undress jobs',
            },
        ),
    ]
