# Generated by Django 3.2.22 on 2024-02-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_packundressjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackUndressJob',
        ),
    ]
