# Generated by Django 3.2.22 on 2024-02-08 10:06

import core.common.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_delete_packundressjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUndressJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='User ID')),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Process'), (2, 'Success'), (-1, 'Error')], default=0, verbose_name='Status')),
                ('detail_status', models.IntegerField(choices=[(0, 'Created parser'), (1, 'Process parser'), (2, 'Success parser'), (3, 'Created make mask'), (4, 'Process make mask'), (5, 'Success make mask'), (6, 'Created job'), (7, 'Process job'), (8, 'Success job'), (-9, 'Error parser'), (-10, 'Error make mask'), (-11, 'Error job'), (-12, 'Expired parser'), (-113, 'Expired make mask'), (14, 'Expired job')], default=0, verbose_name='Detail status')),
                ('link', models.URLField(verbose_name='Account link')),
                ('link_type', models.CharField(choices=[('account', 'Account'), ('photo', 'Photo')], default='account', max_length=255, verbose_name='Link type')),
                ('parser_estimated_time', models.IntegerField(default=60, help_text='In second', verbose_name='Parser estimated time')),
                ('parser_time_spent', models.IntegerField(default=0, help_text='In seconds', verbose_name='Parser time spent')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('jobs', models.ManyToManyField(to='jobs.UndressJob', verbose_name='Jobs')),
            ],
            options={
                'verbose_name': 'Instagram undress job',
                'verbose_name_plural': 'Instagram undress jobs',
            },
        ),
        migrations.CreateModel(
            name='InstagramSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Image url')),
                ('basic_mask', models.ImageField(blank=True, default=None, null=True, upload_to=core.common.utils.PathAndRename('instagram-source-masks/'), verbose_name='Basic mask')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='jobs.instagramundressjob', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Instagram source',
                'verbose_name_plural': 'Instagram sources',
            },
        ),
    ]
