# Generated by Django 3.2.22 on 2024-02-14 21:18

import core.common.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_instagramsource_instagramundressjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.IntegerField(choices=[(0, 'Generate'), (1, 'Undress'), (2, 'Video')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.IntegerField(choices=[(0, 'Generate'), (1, 'Undress'), (2, 'Video')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='jobs.generatejob', verbose_name='Generate job'),
        ),
        migrations.AlterField(
            model_name='sdmodel',
            name='type',
            field=models.IntegerField(choices=[(0, 'Generate'), (1, 'Undress'), (2, 'Video')], verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='User ID')),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Process'), (2, 'Success'), (-1, 'Error')], default=0, verbose_name='Status')),
                ('positive_prompt', models.TextField(default='', verbose_name='Positive prompt')),
                ('negative_prompt', models.TextField(default='', verbose_name='Negative prompt')),
                ('step', models.IntegerField(default=20, verbose_name='Step')),
                ('sampler_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sampler name')),
                ('estimated_time', models.IntegerField(default=60, help_text='In second', verbose_name='Estimated time')),
                ('time_spent', models.IntegerField(default=0, help_text='In seconds', verbose_name='Time spent')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Cost')),
                ('show_in_profile', models.BooleanField(default=False, verbose_name='Show in profile')),
                ('need_watermark', models.BooleanField(default=True, verbose_name='Need watermark')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('video', models.FileField(blank=True, null=True, upload_to=core.common.utils.PathAndRename('video-jobs/'), verbose_name='Image')),
                ('without_watermark_video', models.FileField(blank=True, null=True, upload_to=core.common.utils.PathAndRename('without-watermark-video-jobs/'), verbose_name='Without watermark video')),
                ('filters', models.ManyToManyField(to='jobs.Filter', verbose_name='Filters')),
                ('sd_model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.sdmodel', verbose_name='SD model')),
            ],
            options={
                'verbose_name': 'Video job',
                'verbose_name_plural': 'Video jobs',
            },
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='jobs.videojob', verbose_name='Video job')),
            ],
            options={
                'verbose_name': 'Video Gallery',
                'verbose_name_plural': 'Video Gallery',
            },
        ),
    ]
