# Generated by Django 3.2.22 on 2024-02-15

from django.db import migrations


def forwards_func(apps, schema_editor):
    SDModel = apps.get_model('jobs', 'SDModel')

    SDModel.objects.bulk_create([
        SDModel(
            id=9,
            name='Semi realism (Video)',
            public_name='Semi realism',
            model_name='dreamshaper_8_93211.safetensors',
            type=2,
            raw_prompt='a photo of',
        ),
        SDModel(
            id=10,
            name='Photorealistic (Video)',
            public_name='Photorealistic',
            model_name='dreamshaper_8_93211.safetensors',
            type=2,
            raw_prompt='a photo of',
        ),
        SDModel(
            id=11,
            name='Anime (Video)',
            public_name='Photorealistic',
            model_name='darkSushiMixMix_225D_64380.safetensors',
            type=2,
            raw_prompt='anime draw of',
        ),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0019_auto_20240214_2118'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
