# Generated by Django 3.2.22 on 2024-02-21 16:30

import core.common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_add_video_sd_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='preview',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=core.common.utils.PathAndRename('video-previews/'), verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='videojob',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=core.common.utils.PathAndRename('video-jobs/'), verbose_name='Vidoe'),
        ),
    ]
