# Generated by Django 3.2.22 on 2024-02-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_auto_20240221_1630'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='imagegallery',
            index=models.Index(fields=['job'], name='jobs_imageg_job_id_cb4d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='videogallery',
            index=models.Index(fields=['job'], name='jobs_videog_job_id_8ded4e_idx'),
        ),
    ]
