# Generated by Django 3.2.22 on 2023-10-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='user_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='User ID'),
        ),
    ]
