# Generated by Django 3.2.22 on 2023-10-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231020_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_account',
            field=models.BooleanField(default=False, verbose_name='Deleted account'),
        ),
    ]
