# Generated by Django 3.2.22 on 2023-10-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_deleted_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_before_delete',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Email before delete'),
        ),
    ]
