# Generated by Django 3.2.22 on 2023-10-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20231026_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='patreon',
            name='patreon_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Patreon ID'),
        ),
    ]
