# Generated by Django 3.2.22 on 2023-10-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_patreon_patreon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patreon',
            name='member_id',
            field=models.UUIDField(blank=True, default=None, null=True, verbose_name='Member ID'),
        ),
    ]
