# Generated by Django 3.2.22 on 2023-11-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_patreon_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=255, verbose_name='Auth provider'),
        ),
    ]
