# Generated by Django 3.2.22 on 2023-11-23 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_auth_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlanBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_id', models.CharField(max_length=255, verbose_name='Clik id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alanbase', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Alan Base',
                'verbose_name_plural': 'Alan Base',
            },
        ),
    ]
