# Generated by Django 3.2.22 on 2023-11-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alanbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='alanbase',
            name='sub_id5',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Sub id #5'),
        ),
        migrations.AlterField(
            model_name='alanbase',
            name='click_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Clik id'),
        ),
    ]
