# Generated by Django 3.2.22 on 2024-01-07 12:39

import core.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_anonymoususer'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.users.models.CustomUserManager()),
            ],
        ),
    ]
