# Generated by Django 3.2.22 on 2024-01-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patreon',
        ),
    ]
