# Generated by Django 3.2.22 on 2024-01-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_delete_patreon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('shop', 'Shop')], default='email', max_length=255, verbose_name='Auth provider'),
        ),
    ]
