# Generated by Django 3.2.22 on 2024-02-01

from django.utils import timezone
from django.db import migrations


def forwards_func(apps, schema_editor):
    User = apps.get_model('users', 'User')

    User.objects.filter(auth_provider='google').update(
        email_confirmed=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_auth_provider')
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
