# Generated by Django 3.2.22 on 2024-03-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_update_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='IP address'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_unique_account',
            field=models.BooleanField(default=True, verbose_name='Unique account'),
        ),
    ]
