# Generated by Django 3.2.22 on 2023-10-18 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('preview_image_url', models.URLField(blank=True, default=None, null=True, verbose_name='Preview image url')),
            ],
            options={
                'verbose_name': 'Ai model',
                'verbose_name_plural': 'Ai models',
                'db_table': 'hub_ai_model',
            },
        ),
        migrations.CreateModel(
            name='FilterAction',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter action',
                'verbose_name_plural': 'Filter actions',
                'db_table': 'hub_style__filter_action',
            },
        ),
        migrations.CreateModel(
            name='FilterAge',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter age',
                'verbose_name_plural': 'Filter ages',
                'db_table': 'hub_base__filter_age',
            },
        ),
        migrations.CreateModel(
            name='FilterAngle',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter angle',
                'verbose_name_plural': 'Filter angles',
                'db_table': 'hub_style__filter_angle',
            },
        ),
        migrations.CreateModel(
            name='FilterAss',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter ass',
                'verbose_name_plural': 'Filter asses',
                'db_table': 'hub_body__filter_ass',
            },
        ),
        migrations.CreateModel(
            name='FilterBodyType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter body type',
                'verbose_name_plural': 'Filter body types',
                'db_table': 'hub_body__filter_body_type',
            },
        ),
        migrations.CreateModel(
            name='FilterBreast',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter breast',
                'verbose_name_plural': 'Filter breasts',
                'db_table': 'hub_body__filter_breast',
            },
        ),
        migrations.CreateModel(
            name='FilterClothes',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter clothes',
                'verbose_name_plural': 'Filter clothes',
                'db_table': 'hub_clothes__filter_clothes',
            },
        ),
        migrations.CreateModel(
            name='FilterClothModifier',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter cloth modifier',
                'verbose_name_plural': 'Filter cloth modifiers',
                'db_table': 'hub_clothes__filter_cloth_modifier',
            },
        ),
        migrations.CreateModel(
            name='FilterDistance',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter distance',
                'verbose_name_plural': 'Filter distances',
                'db_table': 'hub_style__filter_distance',
            },
        ),
        migrations.CreateModel(
            name='FilterEthnicity',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter ethnicity',
                'verbose_name_plural': 'Filter ethnicities',
                'db_table': 'hub_base__filter_ethnicity',
            },
        ),
        migrations.CreateModel(
            name='FilterFace',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter face',
                'verbose_name_plural': 'Filter faces',
                'db_table': 'hub_face__filter_face',
            },
        ),
        migrations.CreateModel(
            name='FilterHairColor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter hair color',
                'verbose_name_plural': 'Filter hair colors',
                'db_table': 'hub_face__filter_hair_color',
            },
        ),
        migrations.CreateModel(
            name='FilterHairType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter hair type',
                'verbose_name_plural': 'Filter hair types',
                'db_table': 'hub_face__filter_hair_type',
            },
        ),
        migrations.CreateModel(
            name='FilterLight',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter light',
                'verbose_name_plural': 'Filter lights',
                'db_table': 'hub_style__filter_light',
            },
        ),
        migrations.CreateModel(
            name='FilterModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter model',
                'verbose_name_plural': 'Filter models',
                'db_table': 'hub_base__filter_model',
            },
        ),
        migrations.CreateModel(
            name='FilterNumberOfPeople',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter number of people',
                'verbose_name_plural': 'Filter number of peoples',
                'db_table': 'hub_base__filter_number_of_people',
            },
        ),
        migrations.CreateModel(
            name='FilterSetting',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter setting',
                'verbose_name_plural': 'Filter settings',
                'db_table': 'hub_style__filter_setting',
            },
        ),
        migrations.CreateModel(
            name='FilterSkin',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter skin',
                'verbose_name_plural': 'Filter skins',
                'db_table': 'hub_body__filter_skin',
            },
        ),
        migrations.CreateModel(
            name='FilterStyle',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Filter style',
                'verbose_name_plural': 'Filter styles',
                'db_table': 'hub_style__filter_style',
            },
        ),
        migrations.CreateModel(
            name='PornAction',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('preview_image_url', models.URLField(blank=True, default=None, null=True, verbose_name='Preview image url')),
            ],
            options={
                'verbose_name': 'Porn action',
                'verbose_name_plural': 'Porn actions',
                'db_table': 'hub_porn_action',
            },
        ),
        migrations.CreateModel(
            name='ImageHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(default=None, null=True, verbose_name='Image URL')),
                ('ai_model', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='images_hub', to='hub.aimodel', verbose_name='Ai model')),
                ('filter_action', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='images_hub', to='hub.filteraction', verbose_name='Filter action')),
                ('filter_age', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='images_hub', to='hub.filterage', verbose_name='Filter age')),
                ('filter_angle', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='images_hub', to='hub.filterangle', verbose_name='Filter angle')),
                ('filter_ass', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='images_hub', to='hub.filterass', verbose_name='Filter ass')),
                ('filter_body_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='images_hub', to='hub.filterbodytype', verbose_name='Filter body type')),
                ('filter_breast', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='images_hub', to='hub.filterbreast', verbose_name='Filter breast')),
                ('filter_cloth_modifier', models.ManyToManyField(related_name='images_hub', to='hub.FilterClothModifier', verbose_name='Filter cloth modifier')),
                ('filter_clothes', models.ManyToManyField(related_name='images_hub', to='hub.FilterClothes', verbose_name='Filter clothes')),
                ('filter_distance', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='images_hub', to='hub.filterdistance', verbose_name='Filter distance')),
                ('filter_ethnicity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='images_hub', to='hub.filterethnicity', verbose_name='Filter ethnicity')),
                ('filter_face', models.ManyToManyField(related_name='images_hub', to='hub.FilterFace', verbose_name='Filter face')),
                ('filter_hair_color', models.ManyToManyField(related_name='images_hub', to='hub.FilterHairColor', verbose_name='Filter hair color')),
                ('filter_hair_type', models.ManyToManyField(related_name='images_hub', to='hub.FilterHairType', verbose_name='Filter hair type')),
                ('filter_light', models.ManyToManyField(related_name='images_hub', to='hub.FilterLight', verbose_name='Filter light')),
                ('filter_model', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='images_hub', to='hub.filtermodel', verbose_name='Filter model')),
                ('filter_number_of_people', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='images_hub', to='hub.filternumberofpeople', verbose_name='Filter number of people')),
                ('filter_setting', models.ManyToManyField(related_name='images_hub', to='hub.FilterSetting', verbose_name='Filter setting')),
                ('filter_skin', models.ManyToManyField(related_name='images_hub', to='hub.FilterSkin', verbose_name='Filter skin')),
                ('filter_style', models.ManyToManyField(related_name='images_hub', to='hub.FilterStyle', verbose_name='Filter style')),
                ('porn_action', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='images_hub', to='hub.pornaction', verbose_name='Porn action')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'hub_images',
            },
        ),
    ]
