# Generated by Django 3.2.22 on 2023-10-18 09:40

from django.db import migrations, models
import django.db.models.deletion


def _add_filter_model(apps):
    FilterModel = apps.get_model('hub', 'FilterModel')

    FilterModel.objects.bulk_create([
        FilterModel(id='woman', name='Woman'),
        FilterModel(id='man', name='Man'),
        FilterModel(id='milf', name='Milf'),
        FilterModel(id='transgender', name='Transgender'),
    ])


def _add_filter_number_of_people(apps):
    FilterNumberOfPeople = apps.get_model('hub', 'FilterNumberOfPeople')

    FilterNumberOfPeople.objects.bulk_create([
        FilterNumberOfPeople(id='one', name='One'),
        FilterNumberOfPeople(id='two', name='Two'),
        FilterNumberOfPeople(id='several', name='Several'),
    ])


def _add_filter_age(apps):
    FilterAge = apps.get_model('hub', 'FilterAge')

    FilterAge.objects.bulk_create([
        FilterAge(id='teen', name='18s'),
        FilterAge(id='young', name='20s - 30s'),
        FilterAge(id='milfs', name='40s - 50s'),
        FilterAge(id='old', name='60+'),
    ])


def _add_filter_ethnicity(apps):
    FilterEthnicity = apps.get_model('hub', 'FilterEthnicity')

    FilterEthnicity.objects.bulk_create([
        FilterEthnicity(id='european', name='European'),
        FilterEthnicity(id='black', name='Black'),
        FilterEthnicity(id='white', name='White'),
        FilterEthnicity(id='latina', name='Latina'),
        FilterEthnicity(id='spanish', name='Spanish'),
        FilterEthnicity(id='czech', name='Czech'),
        FilterEthnicity(id='russian', name='Russian'),
        FilterEthnicity(id='african', name='African'),
        FilterEthnicity(id='arabic', name='Arabic'),
        FilterEthnicity(id='asian', name='Asian'),
        FilterEthnicity(id='brazillian', name='Brazillian'),
        FilterEthnicity(id='british', name='British'),
        FilterEthnicity(id='chinese', name='Chinese'),
        FilterEthnicity(id='dutch', name='Dutch'),
        FilterEthnicity(id='egyptian', name='Egyptian'),
        FilterEthnicity(id='ethiopian', name='Ethiopian'),
        FilterEthnicity(id='filipina', name='Filipina'),
        FilterEthnicity(id='french', name='French'),
        FilterEthnicity(id='german', name='German'),
        FilterEthnicity(id='greek', name='Greek'),
        FilterEthnicity(id='hungarian', name='Hungarian'),
        FilterEthnicity(id='indian', name='Indian'),
        FilterEthnicity(id='indonesian', name='Indonesian'),
        FilterEthnicity(id='irish', name='Irish'),
        FilterEthnicity(id='italian', name='Italian'),
        FilterEthnicity(id='japanese', name='Japanese'),
        FilterEthnicity(id='jewish', name='Jewish'),
        FilterEthnicity(id='korean', name='Korean'),
        FilterEthnicity(id='malaysian', name='Malaysian'),
        FilterEthnicity(id='middle_eastern', name='Middle Eastern'),
        FilterEthnicity(id='mongolian', name='Mongolian'),
        FilterEthnicity(id='native_american', name='Native American'),
        FilterEthnicity(id='nigerian', name='Nigerian'),
        FilterEthnicity(id='nilotic', name='Nilotic'),
        FilterEthnicity(id='persian', name='Persian'),
        FilterEthnicity(id='portuguese', name='Portuguese'),
        FilterEthnicity(id='scandinavian', name='Scandinavian'),
        FilterEthnicity(id='swedish', name='Swedish'),
        FilterEthnicity(id='thai', name='Thai'),
        FilterEthnicity(id='turkish', name='Turkish'),
        FilterEthnicity(id='vietnems', name='Vietnems'),
    ])


def _add_filter_body_type(apps):
    FilterBodyType = apps.get_model('hub', 'FilterBodyType')

    FilterBodyType.objects.bulk_create([
        FilterBodyType(id='skinny', name='Skinny'),
        FilterBodyType(id='fit', name='Fit'),
        FilterBodyType(id='fat', name='Fat'),
        FilterBodyType(id='thick', name='Thick'),
        FilterBodyType(id='muscular', name='Muscular'),
    ])


def _add_filter_skin(apps):
    FilterSkin = apps.get_model('hub', 'FilterSkin')

    FilterSkin.objects.bulk_create([
        FilterSkin(id='colored_tattoos', name='Colored tattoos'),
        FilterSkin(id='modern_tattoos', name='Modern tattoos'),
        FilterSkin(id='classic_tattoos', name='Classic tattoos'),
        FilterSkin(id='piercing', name='Piercing'),
        FilterSkin(id='green', name='Green'),
        FilterSkin(id='blue', name='Blue'),
        FilterSkin(id='yellow', name='Yellow'),
        FilterSkin(id='red', name='Red'),
        FilterSkin(id='pink', name='Pink'),
        FilterSkin(id='white', name='White'),
        FilterSkin(id='dark', name='Dark'),
        FilterSkin(id='dark_light', name='Dark light'),
        FilterSkin(id='olied', name='Olied'),
        FilterSkin(id='pale', name='Pale'),
        FilterSkin(id='tanned', name='Tanned'),
    ])


def _add_filter_breast(apps):
    FilterBreast = apps.get_model('hub', 'FilterBreast')

    FilterBreast.objects.bulk_create([
        FilterBreast(id='large', name='Large'),
        FilterBreast(id='big', name='Big'),
        FilterBreast(id='medium', name='Medium'),
        FilterBreast(id='natural', name='Natural'),
        FilterBreast(id='rounded', name='Rounded'),
        FilterBreast(id='small', name='Small'),
    ])


def _add_filter_ass(apps):
    FilterAss = apps.get_model('hub', 'FilterAss')

    FilterAss.objects.bulk_create([
        FilterAss(id='Thick_things', name='Thick things'),
        FilterAss(id='Busty_things', name='Busty things'),
        FilterAss(id='Fit_things', name='Fit things'),
        FilterAss(id='Skinny_things', name='Skinny things'),
        FilterAss(id='big', name='Big'),
        FilterAss(id='large', name='Lare'),
        FilterAss(id='medium', name='Medium'),
        FilterAss(id='rounded', name='Rounded'),
        FilterAss(id='small', name='Small'),
    ])


def _add_filter_face(apps):
    FilterFace = apps.get_model('hub', 'FilterFace')

    FilterFace.objects.bulk_create([
        FilterFace(id='scared', name='Scared'),
        FilterFace(id='seductive_smirk', name='Seductive smirk'),
        FilterFace(id='make_up', name='Make up'),
        FilterFace(id='thick_eyebrows', name='Thick eyebrows'),
        FilterFace(id='long_eyelashes', name='Long eyelashes'),
        FilterFace(id='open_mouth', name='Open mouth'),
        FilterFace(id='serious', name='Serious'),
        FilterFace(id='busty_lips', name='Busty lips'),
        FilterFace(id='big_eyes', name='Big eyes'),
        FilterFace(id='closed_eyes', name='Closed eyes'),
        FilterFace(id='sharp_nose', name='Sharp nose'),
        FilterFace(id='small_nose', name='Small nose'),
        FilterFace(id='wide_jaw', name='Wide jaw'),
        FilterFace(id='narrow_jaw', name='Narrow jaw'),
        FilterFace(id='angry', name='Angry'),
        FilterFace(id='beauty', name='Beauty'),
        FilterFace(id='crying', name='Crying'),
        FilterFace(id='cute', name='Cute'),
        FilterFace(id='horney', name='Horney'),
        FilterFace(id='happy', name='Happy'),
        FilterFace(id='orgasm', name='Orgasm'),
        FilterFace(id='sad', name='Sad'),

    ])


def _add_filter_hair_color(apps):
    FilterHairColor = apps.get_model('hub', 'FilterHairColor')

    FilterHairColor.objects.bulk_create([
        FilterHairColor(id='ombre', name='Ombre'),
        FilterHairColor(id='ash', name='Ash'),
        FilterHairColor(id='black', name='Black'),
        FilterHairColor(id='blonde', name='Blonde'),
        FilterHairColor(id='blue', name='Blue'),
        FilterHairColor(id='brunette', name='Brunette'),
        FilterHairColor(id='ginger', name='Ginger'),
        FilterHairColor(id='gradient', name='Gradient'),
        FilterHairColor(id='green', name='Green'),
        FilterHairColor(id='multicolor', name='Multicolor'),
        FilterHairColor(id='pink', name='Pink'),
        FilterHairColor(id='purple', name='Purple'),
        FilterHairColor(id='white', name='White'),
    ])


def _add_filter_hair_type(apps):
    FilterHairType = apps.get_model('hub', 'FilterHairType')

    FilterHairType.objects.bulk_create([
        FilterHairType(id='bangs', name='Bangs'),
        FilterHairType(id='bobcut', name='Bobcut'),
        FilterHairType(id='braided', name='Braided'),
        FilterHairType(id='curly', name='Curly'),
        FilterHairType(id='fluffy', name='Fluffy'),
        FilterHairType(id='hair_bun', name='Hair bun'),
        FilterHairType(id='long_length', name='Long length'),
        FilterHairType(id='medium_length', name='Medium length'),
        FilterHairType(id='messy', name='Messy'),
        FilterHairType(id='pigtails', name='Pigtails'),
        FilterHairType(id='ponytails', name='Ponytails'),
        FilterHairType(id='public_hair', name='Public hair'),
        FilterHairType(id='short_length', name='Short length'),
        FilterHairType(id='slicked', name='Slicked'),
        FilterHairType(id='straight', name='Straight'),
    ])


def _add_filter_clothes(apps):
    FilterClothes = apps.get_model('hub', 'FilterClothes')

    FilterClothes.objects.bulk_create([
        FilterClothes(id='hijab', name='Hijab'),
        FilterClothes(id='beanie', name='Beanie'),
        FilterClothes(id='hat', name='Hat'),
        FilterClothes(id='glasses', name='Glasses'),
        FilterClothes(id='sunglasses', name='Sunglasses'),
        FilterClothes(id='kerchief', name='Kerchief'),
        FilterClothes(id='babushka', name='Babushka'),
        FilterClothes(id='neckerchief', name='Neckerchief'),
        FilterClothes(id='antique_clothing', name='Antique clothing'),
        FilterClothes(id='prehistoric_clothes', name='Prehistoric clothes'),
        FilterClothes(id='tribal_clothing', name='Tribal clothing'),
        FilterClothes(id='naked', name='Naked'),
        FilterClothes(id='angel', name='Angel'),
        FilterClothes(id='apron', name='Apron'),
        FilterClothes(id='armor', name='Armor'),
        FilterClothes(id='armor_gloves', name='Armor gloves'),
        FilterClothes(id='basketball', name='Basketball'),
        FilterClothes(id='bathrobe', name='Bathrobe'),
        FilterClothes(id='bikini', name='Bikini'),
        FilterClothes(id='blouse', name='Blouse'),
        FilterClothes(id='bodysuit', name='Bodysuit'),
        FilterClothes(id='bone_mask', name='Bone mask'),
        FilterClothes(id='boots', name='Boots'),
        FilterClothes(id='bra', name='Bra'),
        FilterClothes(id='carnival_mask', name='Carnival mask'),
        FilterClothes(id='carnival_suit', name='Carnival suit'),
        FilterClothes(id='casual', name='Casual'),
        FilterClothes(id='choker', name='Choker'),
        FilterClothes(id='christmas', name='Christmas'),
        FilterClothes(id='clow', name='Clow'),
        FilterClothes(id='corset', name='Corset'),
        FilterClothes(id='cosplay', name='Cosplay'),
        FilterClothes(id='cotton_shorts', name='Cotton shorts'),
        FilterClothes(id='diadem', name='Diadem'),
        FilterClothes(id='dress', name='Dress'),
        FilterClothes(id='evenig_ball_mask', name='Evenig ball mask'),
        FilterClothes(id='facemask', name='Facemask'),
        FilterClothes(id='firefighter', name='Firefighter'),
        FilterClothes(id='halloween', name='Halloween'),
        FilterClothes(id='headphones', name='Headphones'),
        FilterClothes(id='hoodie', name='Hoodie'),
        FilterClothes(id='jacket', name='Jacket'),
        FilterClothes(id='jeans', name='Jeans'),
        FilterClothes(id='jeans_shorts', name='Jeans shorts'),
        FilterClothes(id='long_sleeves', name='Long sleeves'),
        FilterClothes(id='medieval', name='Medieval'),
        FilterClothes(id='military', name='Military'),
        FilterClothes(id='mini_skirt', name='Mini skirt'),
        FilterClothes(id='mistress', name='Mistress'),
        FilterClothes(id='necklace', name='Necklace'),
        FilterClothes(id='ninja', name='Ninja'),
        FilterClothes(id='nurse', name='Nurse'),
        FilterClothes(id='nylon_gloves', name='Nylon Gloves'),
        FilterClothes(id='nylon_stockings', name='Nylon stockings'),
        FilterClothes(id='office_pants', name='Office pants'),
        FilterClothes(id='office_shirt', name='Office shirt'),
        FilterClothes(id='pajamas', name='Pajamas'),
        FilterClothes(id='police_costume', name='Police costume'),
        FilterClothes(id='pullover', name='Pullover'),
        FilterClothes(id='sc_fi', name='Sc-fi'),
        FilterClothes(id='sleeveless_tshirt', name='Sleeveless t-shirt'),
        FilterClothes(id='scarf', name='Scarf'),
        FilterClothes(id='skirt', name='Skirt'),
        FilterClothes(id='sport_bra', name='Sport Bra'),
        FilterClothes(id='steampunk', name='Steampunk'),
        FilterClothes(id='stockings', name='Stockings'),
        FilterClothes(id='superhero', name='Superhero'),
        FilterClothes(id='suspenders', name='Suspenders'),
        FilterClothes(id='sweater', name='Sweater'),
        FilterClothes(id='swimsuit', name='Swimsuit'),
        FilterClothes(id='tailcoat', name='Tailcoat'),
        FilterClothes(id='teacher', name='Teacher'),
        FilterClothes(id='thong', name='Thong'),
        FilterClothes(id='tight_top', name='Tight top'),

        FilterClothes(id='topless', name='Topless'),
        FilterClothes(id='tunic', name='Tunic'),
        FilterClothes(id='underpants', name='Underpants'),
        FilterClothes(id='viking', name='Viking'),
        FilterClothes(id='western', name='Western'),
        FilterClothes(id='witch', name='Witch'),
        FilterClothes(id='without_pants', name='Without pants'),
        FilterClothes(id='yoga_pants', name='Yoga pants'),
    ])


def _add_filter_cloth_modifier(apps):
    FilterClothModifier = apps.get_model('hub', 'FilterClothModifier')

    FilterClothModifier.objects.bulk_create([
        FilterClothModifier(id='naked', name='Naked'),
        FilterClothModifier(id='intricate_clothes', name='Intricate clothes'),
        FilterClothModifier(id='neckline', name='Neckline'),
        FilterClothModifier(id='transparent', name='Transparent'),
        FilterClothModifier(id='unbuttoned', name='Unbuttoned'),
        FilterClothModifier(id='unzipped', name='Unzipped'),
        FilterClothModifier(id='lingerie', name='Lingerie'),
        FilterClothModifier(id='bdsm', name='BDSM'),
        FilterClothModifier(id='inventory_for_sex', name='Inventory for sex'),
    ])


def _add_filter_distance(apps):
    FilterDistance = apps.get_model('hub', 'FilterDistance')

    FilterDistance.objects.bulk_create([
        FilterDistance(id='fisheye_camera', name='Fisheye camera'),
        FilterDistance(id='selfie', name='Selfie'),
        FilterDistance(id='closeup_portrait', name='Closeup Portrait'),
        FilterDistance(id='full_body', name='Full Body'),
        FilterDistance(id='portrait', name='Portrait'),
    ])


def _add_filter_angle(apps):
    FilterAngle = apps.get_model('hub', 'FilterAngle')

    FilterAngle.objects.bulk_create([
        FilterAngle(id='view_from_below', name='View from below'),
        FilterAngle(id='dynamic', name='Dynamic'),
        FilterAngle(id='low', name='Low'),
        FilterAngle(id='view_from_above', name='View from above'),
    ])


def _add_filter_action(apps):
    FilterAction = apps.get_model('hub', 'FilterAction')

    FilterAction.objects.bulk_create([
        FilterAction(id='seductive_pose', name='Seductive pose'),
        FilterAction(id='striptease', name='Striptease'),
        FilterAction(id='on_all_fours', name='On all fours'),
        FilterAction(id='on_back', name='On back'),
        FilterAction(id='on_stomach', name='On stomach'),
        FilterAction(id='on_side', name='On side'),
        FilterAction(id='crawl', name='Crawl'),
        FilterAction(id='dance', name='Dance'),
        FilterAction(id='laying', name='Laying'),
        FilterAction(id='model', name='Model'),
        FilterAction(id='spreaded_legs', name='Spreaded legs'),
        FilterAction(id='squatting', name='Squatting'),
        FilterAction(id='standing', name='Standing'),
        FilterAction(id='yoga', name='Yoga'),

    ])


def _add_filter_setting(apps):
    FilterSetting = apps.get_model('hub', 'FilterSetting')

    FilterSetting.objects.bulk_create([
        FilterSetting(id='laboratory', name='Laboratory'),
        FilterSetting(id='winter', name='Winter'),
        FilterSetting(id='autumn', name='Autumn'),
        FilterSetting(id='spring', name='Spring'),
        FilterSetting(id='summer', name='Summer'),
        FilterSetting(id='wood_cabin', name='Wood cabin'),
        FilterSetting(id='castle', name='Castle'),
        FilterSetting(id='swamp', name='Swamp'),
        FilterSetting(id='river', name='River'),
        FilterSetting(id='blooming_garden', name='Blooming garden'),
        FilterSetting(id='space', name='Space'),
        FilterSetting(id='milkyway', name='Milkyway'),
        FilterSetting(id='ancient_city', name='Ancient city'),
        FilterSetting(id='bar', name='Bar'),
        FilterSetting(id='bathroom', name='Bathroom'),
        FilterSetting(id='battlefield', name='Battlefield'),
        FilterSetting(id='beach', name='Beach'),
        FilterSetting(id='bed', name='Bed'),
        FilterSetting(id='bus', name='Bus'),
        FilterSetting(id='cafe', name='Cafe'),
        FilterSetting(id='car', name='Car'),
        FilterSetting(id='carnival_street', name='Carnival street'),
        FilterSetting(id='casino', name='Casino'),
        FilterSetting(id='cave', name='Cave'),
        FilterSetting(id='changing_room', name='Changing room'),
        FilterSetting(id='church', name='Church'),
        FilterSetting(id='city', name='City'),
        FilterSetting(id='club', name='Club'),
        FilterSetting(id='couch', name='Couch'),
        FilterSetting(id='cyberpunk_city', name='Cyberpunk city'),
        FilterSetting(id='desert', name='Desert'),
        FilterSetting(id='forest', name='Forest'),
        FilterSetting(id='galaxy', name='Galaxy'),
        FilterSetting(id='grocery', name='Grocery'),
        FilterSetting(id='gym', name='Gym'),
        FilterSetting(id='hospital', name='Hospital'),
        FilterSetting(id='hot_tub', name='Hot tub'),
        FilterSetting(id='jungle', name='Jungle'),
        FilterSetting(id='kitchen', name='Kitchen'),
        FilterSetting(id='lake', name='Lake'),
        FilterSetting(id='locker_room', name='Locker room'),
        FilterSetting(id='mall', name='Mall'),
        FilterSetting(id='meadow', name='Meadow'),
        FilterSetting(id='modern_city', name='Modern city'),
        FilterSetting(id='moon', name='Moon'),
        FilterSetting(id='mountains', name='Mountains'),
        FilterSetting(id='oasis', name='Oasis'),
        FilterSetting(id='office', name='Office'),
        FilterSetting(id='onsen', name='Onsen'),
        FilterSetting(id='party', name='Party'),
        FilterSetting(id='pool', name='Pool'),
        FilterSetting(id='prison', name='Prison'),
        FilterSetting(id='restaurant', name='Restaurant'),
        FilterSetting(id='sauna', name='Sauna'),
        FilterSetting(id='shower', name='Shower'),
        FilterSetting(id='snow', name='Snow'),
        FilterSetting(id='stage', name='Stage'),
        FilterSetting(id='street', name='Street'),
        FilterSetting(id='strip_club', name='Strip club'),
        FilterSetting(id='tent', name='Tent'),
        FilterSetting(id='train', name='Train'),
        FilterSetting(id='underwater', name='Underwater'),
        FilterSetting(id='sedding', name='Sedding'),
        FilterSetting(id='yacht', name='Yacht'),

    ])


def _add_filter_light(apps):
    FilterLight = apps.get_model('hub', 'FilterLight')

    FilterLight.objects.bulk_create([
        FilterLight(id='golden_dust', name='Golden dust'),
        FilterLight(id='dimly_lit', name='Dimly lit'),
        FilterLight(id='foggy', name='Foggy'),
        FilterLight(id='cinematic', name='Cinematic'),
        FilterLight(id='contre_jour', name='Contre-jour'),
        FilterLight(id='dark_scene', name='Dark scene'),
        FilterLight(id='day', name='Day'),
        FilterLight(id='hard', name='Hard'),
        FilterLight(id='low', name='Low'),
        FilterLight(id='moon', name='Moon'),
        FilterLight(id='rim', name='Rim'),
        FilterLight(id='single', name='Single'),
        FilterLight(id='soft', name='Soft'),
        FilterLight(id='spotlight', name='Spotlight'),
        FilterLight(id='straight', name='Straight'),
        FilterLight(id='studio', name='Studio'),
        FilterLight(id='warm', name='Warm'),
    ])


def _add_filter_style(apps):
    FilterStyle = apps.get_model('hub', 'FilterStyle')

    FilterStyle.objects.bulk_create([
        FilterStyle(id='neoclassicism', name='Neoclassicism'),
        FilterStyle(id='makoto_shinkai', name='Makoto Shinkai'),
        FilterStyle(id='sam_spratt', name='Sam Spratt'),
        FilterStyle(id='ed_binkley', name='Ed Binkley'),
        FilterStyle(id='john_berkey', name='John Berkey'),
        FilterStyle(id='angus_mckie', name='Angus McKie'),
        FilterStyle(id='shohei_otomo', name='Shohei Otomo'),
        FilterStyle(id='eddie_mendoza', name='Eddie Mendoza'),
        FilterStyle(id='posuka_demizu', name='Posuka Demizu'),
        FilterStyle(id='rebecca_sugar', name='Rebecca Sugar'),
        FilterStyle(id='laurie_greasley', name='Laurie Greasley'),
        FilterStyle(id='jordan_grimmer', name='Jordan Grimmer'),
        FilterStyle(id='greg_rutkowski', name='Greg Rutkowski'),
        FilterStyle(id='bokeh', name='Bokeh'),
        FilterStyle(id='2d', name='2D'),
        FilterStyle(id='3d', name='3D'),
        FilterStyle(id='80s_photo', name='80s Photo'),
        FilterStyle(id='anime', name='Anime'),
        FilterStyle(id='b&w', name='B&W'),
        FilterStyle(id='dark_souls', name='Dark souls'),
        FilterStyle(id='digital_art', name='Digital art'),
        FilterStyle(id='disney_cartoon', name='Disney cartoon'),
        FilterStyle(id='drawing_splash_art', name='Drawing splash art'),
        FilterStyle(id='fantasy', name='Fantasy'),
        FilterStyle(id='film_grain', name='Film grain'),
        FilterStyle(id='marvel', name='Marvel'),
        FilterStyle(id='masterpiece', name='Masterpiece'),
        FilterStyle(id='noir', name='Noir'),
        FilterStyle(id='octane ', name='Octane Render'),
        FilterStyle(id='oil ', name='Oil painting'),
        FilterStyle(id='realism', name='Realism'),
        FilterStyle(id='sketch ', name='Sketch lines'),
        FilterStyle(id='unreal ', name='Unreal Engine'),
    ])


def _add_ai_model(apps):
    AiModel = apps.get_model('hub', 'AiModel')

    AiModel.objects.bulk_create([
        AiModel(id='semi_realism', name='Semi-Realism'),
        AiModel(id='photo_realism', name='Photo realism'),
        AiModel(id='asian_realism', name='Asian realism'),
        AiModel(id='anime', name='Anime'),
    ])


def _add_pron_action(apps):
    PornAction = apps.get_model('hub', 'PornAction')

    PornAction.objects.bulk_create([
        PornAction(id='default', name='Default'),
    ])


def forwards_func(apps, schema_editor):
    _add_filter_model(apps)
    _add_filter_number_of_people(apps)
    _add_filter_age(apps)
    _add_filter_ethnicity(apps)

    _add_filter_body_type(apps)
    _add_filter_skin(apps)
    _add_filter_breast(apps)
    _add_filter_ass(apps)

    _add_filter_face(apps)
    _add_filter_hair_color(apps)
    _add_filter_hair_type(apps)

    _add_filter_clothes(apps)
    _add_filter_cloth_modifier(apps)

    _add_filter_distance(apps)
    _add_filter_angle(apps)
    _add_filter_action(apps)
    _add_filter_setting(apps)
    _add_filter_light(apps)
    _add_filter_style(apps)

    _add_ai_model(apps)
    _add_pron_action(apps)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
