# Generated by Django 3.2.22 on 2023-11-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_add_base_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagehub',
            name='show_in_hub',
            field=models.BooleanField(default=True, verbose_name='Show in hub'),
        ),
    ]
