# Generated by Django 3.2.22 on 2023-11-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_imagehub_show_in_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehub',
            name='filter_cloth_modifier',
            field=models.ManyToManyField(blank=True, related_name='images_hub', to='hub.FilterClothModifier', verbose_name='Filter cloth modifier'),
        ),
        migrations.AlterField(
            model_name='imagehub',
            name='filter_clothes',
            field=models.ManyToManyField(blank=True, related_name='images_hub', to='hub.FilterClothes', verbose_name='Filter clothes'),
        ),
        migrations.AlterField(
            model_name='imagehub',
            name='filter_face',
            field=models.ManyToManyField(blank=True, related_name='images_hub', to='hub.FilterFace', verbose_name='Filter face'),
        ),
        migrations.AlterField(
            model_name='imagehub',
            name='filter_hair_color',
            field=models.ManyToManyField(blank=True, related_name='images_hub', to='hub.FilterHairColor', verbose_name='Filter hair color'),
        ),
        migrations.AlterField(
            model_name='imagehub',
            name='filter_hair_type',
            field=models.ManyToManyField(blank=True, related_name='images_hub', to='hub.FilterHairType', verbose_name='Filter hair type'),
        ),
        migrations.AlterField(
            model_name='imagehub',
            name='filter_light',
            field=models.ManyToManyField(blank=True, related_name='images_hub', to='hub.FilterLight', verbose_name='Filter light'),
        ),
        migrations.AlterField(
            model_name='imagehub',
            name='filter_setting',
            field=models.ManyToManyField(blank=True, related_name='images_hub', to='hub.FilterSetting', verbose_name='Filter setting'),
        ),
        migrations.AlterField(
            model_name='imagehub',
            name='filter_skin',
            field=models.ManyToManyField(blank=True, related_name='images_hub', to='hub.FilterSkin', verbose_name='Filter skin'),
        ),
        migrations.AlterField(
            model_name='imagehub',
            name='filter_style',
            field=models.ManyToManyField(blank=True, related_name='images_hub', to='hub.FilterStyle', verbose_name='Filter style'),
        ),
    ]
