# Generated by Django 3.2.22 on 2023-10-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user_id', models.CharField(max_length=10, verbose_name='User ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Answered'), (-1, 'Cancel')], default=0, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Support message',
                'verbose_name_plural': 'Support message',
            },
        ),
    ]
