# Generated by Django 3.2.22 on 2023-10-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
