# Generated by Django 4.2.5 on 2023-10-16 14:55

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Subscription = apps.get_model('subscriptions', 'Subscription')

    Subscription.objects.bulk_create([
        Subscription(
            id=1,
            title='Free',
            uniq_name='free',
            service_path='apps.subscriptions.services.FreeSubscriptionService',
        ),
        Subscription(
            id=2,
            title='Basic',
            uniq_name='basic',
            service_path='apps.subscriptions.services.BasicSubscriptionService',
        ),
        Subscription(
            id=3,
            title='Premium',
            uniq_name='premium',
            service_path='apps.subscriptions.services.PremiumSubscriptionService',
        ),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
