# Generated by Django 4.2.5 on 2023-10-16 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_add_base_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, verbose_name='User id')),
                ('start_period', models.DateTimeField(auto_now=True, verbose_name='Start period')),
                ('end_period', models.DateTimeField(verbose_name='End period')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.subscription', verbose_name='Subscription')),
            ],
            options={
                'verbose_name': 'User subscription',
                'verbose_name_plural': 'User subscriptions',
            },
        ),
    ]
