# Generated by Django 4.2.5 on 2023-10-16 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_usersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusiveOpportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('uniq_name', models.CharField(max_length=255, unique=True, verbose_name='Unique name')),
                ('service_path', models.CharField(max_length=255, verbose_name='Service path')),
            ],
            options={
                'verbose_name': 'Exclusive opportunities',
                'verbose_name_plural': 'Exclusive opportunities',
            },
        ),
        migrations.CreateModel(
            name='UserExclusiveOpportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, verbose_name='User id')),
                ('start_period', models.DateTimeField(auto_now=True, verbose_name='Start period')),
                ('end_period', models.DateTimeField(verbose_name='End period')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('exclusive_opportunities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_opportunities', to='subscriptions.exclusiveopportunities', verbose_name='Exclusive opportunities')),
            ],
            options={
                'verbose_name': 'User exclusive opportunities',
                'verbose_name_plural': 'User exclusive opportunities',
            },
        ),
    ]
