# Generated by Django 4.2.5 on 2023-10-16 14:55

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    ExclusiveOpportunities = apps.get_model('subscriptions', 'ExclusiveOpportunities')

    ExclusiveOpportunities.objects.bulk_create([
        ExclusiveOpportunities(
            id=1,
            title='Unlimited undress 1 day',
            uniq_name='unlimited:undress:lvl1',
            service_path='apps.subscriptions.exclusive_opportunities.UnlimitedUndressGeneratorLVL1',
        ),
        ExclusiveOpportunities(
            id=2,
            title='Unlimited undress 3 day',
            uniq_name='unlimited:undress:lvl2',
            service_path='apps.subscriptions.exclusive_opportunities.UnlimitedUndressGeneratorLVL2',
        ),
        ExclusiveOpportunities(
            id=3,
            title='Unlimited undress 7 day',
            uniq_name='unlimited:undress:lvl3',
            service_path='apps.subscriptions.exclusive_opportunities.UnlimitedUndressGeneratorLVL3',
        ),
        ExclusiveOpportunities(
            id=4,
            title='Extra undress credits Basic',
            uniq_name='extra:credits:undress:lvl1',
            service_path='apps.subscriptions.exclusive_opportunities.ExtraUndressCreditsLVL1',
        ),
        ExclusiveOpportunities(
            id=5,
            title='Extra undress credits Premium',
            uniq_name='extra:credits:undress:lvl2',
            service_path='apps.subscriptions.exclusive_opportunities.ExtraUndressCreditsLVL2',
        ),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0004_exclusiveopportunities_userexclusiveopportunities'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
