# Generated by Django 4.2.5 on 2023-10-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_add_base_exclusive_opportunities'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusiveopportunities',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=255, verbose_name='Price USD'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=255, verbose_name='Price USD'),
        ),
    ]
