# Generated by Django 4.2.5 on 2023-10-17 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_exclusiveopportunities_price_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexclusiveopportunities',
            name='start_period',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start period'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_period',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start period'),
        ),
    ]
