# Generated by Django 4.2.5 on 2023-10-16 14:55
import decimal

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Subscription = apps.get_model('subscriptions', 'Subscription')

    Subscription.objects.bulk_create([
        Subscription(
            id=4,
            price_usd=decimal.Decimal('69.99'),
            title='Premium (12 months)',
            uniq_name='ultra_premium',
            service_path='apps.subscriptions.services.UltraPremiumSubscriptionService',
        ),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0007_alter_userexclusiveopportunities_start_period_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
