# Generated by Django 3.2.22 on 2023-11-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_add_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexclusiveopportunities',
            name='exclusive_opportunities',
        ),
        migrations.DeleteModel(
            name='ExclusiveOpportunities',
        ),
        migrations.DeleteModel(
            name='UserExclusiveOpportunities',
        ),
    ]
