# Generated by Django 3.2.22 on 2024-02-02 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('first_event_2024', 'First Event (Free tokens)')], max_length=255, verbose_name='Event')),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Sent'), (2, 'Success'), (3, 'Expired'), (-1, 'Error')], default=0, verbose_name='Status')),
                ('secret_code', models.CharField(max_length=255, unique=True, verbose_name='Secret code')),
                ('expiry_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Expiry at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Event message',
                'verbose_name_plural': 'Event messages',
            },
        ),
    ]
