# Generated by Django 3.2.22 on 2023-10-20 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IvendpayInvoice',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Order ID')),
                ('invoice_id', models.CharField(max_length=255, unique=True, verbose_name='Invoice id')),
                ('payment_url', models.URLField(verbose_name='Payment url')),
                ('currency', models.CharField(max_length=255, verbose_name='Crypto currency')),
                ('amount', models.DecimalField(decimal_places=25, max_digits=25, verbose_name='Crypto amount')),
                ('status', models.CharField(choices=[('WAITING_FOR_PAYMENT', 'Waiting for payment'), ('PAID', 'Paid'), ('TIMEOUT', 'Timeout')], default='WAITING_FOR_PAYMENT', max_length=255, verbose_name='Status')),
                ('expiry_at', models.DateTimeField(verbose_name='Expiry At')),
            ],
            options={
                'verbose_name': 'Ivendpay order',
                'verbose_name_plural': 'Ivendpay orders',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Order id')),
                ('product_id', models.IntegerField(verbose_name='Product ID')),
                ('type', models.IntegerField(choices=[(0, 'Subscription'), (1, 'Exclusive opportunities')], default=0, verbose_name='Order type')),
                ('payment_type', models.CharField(choices=[('ivendpay', 'Ivendpay')], default='ivendpay', max_length=255, verbose_name='Crypto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Amount')),
                ('fiat_currency', models.CharField(max_length=255, verbose_name='Fiat currency')),
                ('status', models.IntegerField(choices=[(0, 'Created'), (2, 'Paid'), (-1, 'Cancel'), (-2, 'Error')], default=0, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
