# Generated by Django 3.2.22 on 2023-10-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivendpayinvoice',
            name='explorer_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Transaction hash'),
        ),
        migrations.AddField(
            model_name='ivendpayinvoice',
            name='transaction_hash',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Transaction hash'),
        ),
        migrations.AlterField(
            model_name='ivendpayinvoice',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_PAYMENT', 'Waiting for payment'), ('PAID', 'Paid'), ('TIMEOUT', 'Timeout'), ('CANCELED', 'Canceled')], default='WAITING_FOR_PAYMENT', max_length=255, verbose_name='Status'),
        ),
    ]
