# Generated by Django 3.2.22 on 2023-10-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20231020_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivendpayinvoice',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=25, verbose_name='Crypto amount'),
        ),
    ]
