# Generated by Django 3.2.22 on 2023-11-13 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_ivendpayinvoice_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalInvoice',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Order ID')),
                ('invoice_id', models.CharField(max_length=255, unique=True, verbose_name='Invoice id')),
                ('payment_url', models.URLField(verbose_name='Payment url')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SAVED', 'Saved'), ('APPROVED', 'Approved'), ('VOIDED', 'Voided'), ('COMPLETED', 'Competed'), ('PAYER_ACTION_REQUIRED', 'Payer action required')], default='CREATED', max_length=255, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Paypal invoice',
                'verbose_name_plural': 'Paypal invoices',
            },
        ),
        migrations.AlterModelOptions(
            name='ivendpayinvoice',
            options={'verbose_name': 'Ivendpay invoice', 'verbose_name_plural': 'Ivendpay invoices'},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('ivendpay', 'Ivendpay'), ('paypal', 'Paypal')], default='ivendpay', max_length=255, verbose_name='Crypto'),
        ),
    ]
