# Generated by Django 3.2.22 on 2023-11-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20231114_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.IntegerField(choices=[(0, 'Subscription'), (1, 'Exclusive opportunities'), (2, 'Token')], default=0, verbose_name='Order type'),
        ),
    ]
