# Generated by Django 3.2.22 on 2023-11-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.IntegerField(choices=[(0, 'Subscription'), (1, 'Token')], default=0, verbose_name='Order type'),
        ),
    ]
