# Generated by Django 3.2.22 on 2023-11-21 12:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_subscription_active'),
        ('payments', '0007_alter_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalBillingPlan',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(help_text='ID in PayPal', max_length=255, verbose_name='ID')),
                ('fiat_currency', models.CharField(max_length=255, verbose_name='Fiat currency')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_plans', to='subscriptions.subscription', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'PayPal Billing Plan',
                'verbose_name_plural': 'PayPal Billing Plans (subscription)',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('ivendpay', 'Ivendpay'), ('paypal', 'Paypal'), ('paypal_subscription', 'Paypal Subscription')], default='ivendpay', max_length=255, verbose_name='Payment Type'),
        ),
        migrations.CreateModel(
            name='PayPalSubscriptionInvoice',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Order ID')),
                ('invoice_id', models.CharField(max_length=255, unique=True, verbose_name='Invoice id')),
                ('payment_url', models.URLField(blank=True, default=None, null=True, verbose_name='Payment url')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SUCCESS', 'Success'), ('TIMEOUT', 'Timeout')], default='CREATED', max_length=255, verbose_name='Status')),
                ('expiry_at', models.DateTimeField(default=None, null=True, verbose_name='Expiry At')),
                ('billing_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='payments.paypalbillingplan', verbose_name='Billing plan')),
            ],
            options={
                'verbose_name': 'PayPal Subscription invoice',
                'verbose_name_plural': 'PayPal Subscription invoices',
            },
        ),
    ]
