# Generated by Django 3.2.22 on 2023-11-22 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20231121_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatreonSubscriptionInvoice',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Order ID')),
                ('invoice_id', models.CharField(max_length=255, unique=True, verbose_name='Invoice id')),
                ('payment_url', models.URLField(blank=True, default=None, null=True, verbose_name='Payment url')),
                ('status', models.CharField(choices=[('PAID', 'Paid')], default='PAID', max_length=255, verbose_name='Status')),
                ('expiry_at', models.DateTimeField(default=None, null=True, verbose_name='Expiry At')),
            ],
            options={
                'verbose_name': 'Patreon (subscription) invoice',
                'verbose_name_plural': 'Patreon (subscription) invoices',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('ivendpay', 'Ivendpay'), ('paypal', 'Paypal'), ('paypal_subscription', 'Paypal (subscription)'), ('patreon', 'Patreon (subscription)')], default='ivendpay', max_length=255, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='paypalsubscriptioninvoice',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success')], default='SUCCESS', max_length=255, verbose_name='Status'),
        ),
    ]
