# Generated by Django 3.2.22 on 2023-11-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20231122_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalsubscriptioninvoice',
            name='subscription_id',
            field=models.CharField(default=None, help_text='PayPal subscription id', max_length=255, null=True, verbose_name='Subscription id'),
        ),
    ]
