# Generated by Django 3.2.22 on 2023-11-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_paypalsubscriptioninvoice_subscription_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ivendpayinvoice',
            options={'verbose_name': 'IvendPay invoice', 'verbose_name_plural': 'IvendPay invoices'},
        ),
        migrations.AlterModelOptions(
            name='paypalinvoice',
            options={'verbose_name': 'PayPal invoice', 'verbose_name_plural': 'PayPal invoices'},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('ivendpay', 'IvendPay'), ('paypal', 'PayPal'), ('paypal_subscription', 'PayPal (subscription)'), ('patreon', 'Patreon (subscription)')], default='ivendpay', max_length=255, verbose_name='Payment Type'),
        ),
    ]
