# Generated by Django 3.2.22 on 2023-12-06 09:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20231123_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayAdmitInvoice',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Order ID')),
                ('invoice_id', models.CharField(max_length=255, unique=True, verbose_name='Invoice id')),
                ('payment_url', models.URLField(blank=True, default=None, null=True, verbose_name='Payment url')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('CANCEL', 'Cancel'), ('TIMEOUT', 'Timeout'), ('ERROR', 'Error')], default='CREATED', max_length=255, verbose_name='Status')),
                ('payment_method', models.CharField(help_text='From PayAdmit', max_length=255, verbose_name='Payment method')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='Amount')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Currency')),
                ('expiry_at', models.DateTimeField(default=None, null=True, verbose_name='Expiry At')),
            ],
            options={
                'verbose_name': 'PayAdmit invoice',
                'verbose_name_plural': 'PayAdmit invoices',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('ivendpay', 'IvendPay'), ('paypal', 'PayPal'), ('paypal_subscription', 'PayPal (subscription)'), ('patreon', 'Patreon (subscription)'), ('payadmit', 'PayAdmit')], default='ivendpay', max_length=255, verbose_name='Payment Type'),
        ),
    ]
