# Generated by Django 4.2.5 on 2023-10-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Image id')),
                ('user_id', models.CharField(max_length=10, verbose_name='User ID')),
                ('image_url', models.URLField(default=None, null=True, verbose_name='Image url')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('prompt', models.CharField(max_length=500, verbose_name='Prompt')),
            ],
            options={
                'verbose_name': 'Generation job',
                'verbose_name_plural': 'Generation jobs',
            },
        ),
        migrations.CreateModel(
            name='UndressJob',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Image id')),
                ('user_id', models.CharField(max_length=10, verbose_name='User ID')),
                ('image_url', models.URLField(default=None, null=True, verbose_name='Image url')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Undress job',
                'verbose_name_plural': 'Undress jobs',
            },
        ),
    ]
