# Generated by Django 3.2.22 on 2023-11-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_generationjob_has_blur'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='show_in_profile',
            field=models.BooleanField(default=True, verbose_name='Show in profile'),
        ),
    ]
