# Generated by Django 3.2.22 on 2023-12-26 14:59

import apps.profiles.models
import core.common.mixins
import core.common.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('users', '0011_auto_20231127_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='users.user', verbose_name='User')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=core.common.utils.PathAndRename('profiles/'), verbose_name='Image')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Balance')),
                ('type', models.CharField(choices=[('basic', 'Basic'), ('advance', 'Advance'), ('premium', 'Premium'), ('super_premium', 'Super Premium')], default='basic', max_length=255, verbose_name='Type')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deleted')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
            bases=(core.common.mixins.ImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProfileSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('start_period', models.DateTimeField(auto_now_add=True, verbose_name='Start period')),
                ('end_period', models.DateTimeField(blank=True, null=True, verbose_name='End period')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='profiles.profile', verbose_name='Profile')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profiles', to='shop.product', validators=[apps.profiles.models.profile_subscription_validator], verbose_name='Subscription product')),
            ],
            options={
                'verbose_name': 'Profile subscription',
                'verbose_name_plural': 'Profiles subscription',
            },
        ),
    ]
