# Generated by Django 3.2.22 on 2023-12-28 15:23

from django.utils import timezone
from django.db import migrations


def forwards_func(apps, schema_editor):
    """
    1. Для user с pk=1 free subscription:
        - Создаем профиль с типом basic
        - Даем на баланс 1 токен

    2. Для user с pk=3 premium subscription:
        - Создаем профиль с типом premium
        - Создаем подписку с типом Product 3
            - ProfileSubscription.subscription_id = 3
            - is_active = True
            - start_period = now
            - end_period = UserSubscription.end_period
        - Добовляем баланс + (90 - get_undress_credits_left_by_user)

    3. Для user с pk=4 ultra premium subscription
        - Создаем профиль с типом super_premium
        - Создаем подписку с типом Product 5
            - ProfileSubscription.subscription_id = 5
            - is_active = True
            - start_period = now
            - end_period = UserSubscription.end_period
        - Добовляем баланс + (1080 - get_undress_credits_left_by_user)
    """

    User = apps.get_model('users', 'User')

    Profile = apps.get_model('profiles', 'Profile')

    profile_objs = []
    for user in User.objects.filter(deleted_account=False):
        profile_objs.append(Profile(owner=user, balance=1))


    Profile.objects.bulk_create(profile_objs)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profilesubscription_profile'),
        ('users', '0011_auto_20231127_1539'),
        ('subscriptions', '0010_subscription_active'),
        ('shop', '0002_add_base_products'),
        ('accounts', '0004_generationjob_show_in_profile'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
