# Generated by Django 3.2.22 on 2024-02-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=25, verbose_name='Balance'),
        ),
    ]
