# Generated by Django 3.2.22 on 2023-12-28 15:23
import decimal

from django.utils import timezone
from django.db import migrations


def forwards_func(apps, schema_editor):
    Profile = apps.get_model('profiles', 'Profile')

    for profile in Profile.objects.filter(
        balance__gt=0,
    ):
        profile.balance *= decimal.Decimal('10')
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profile_balance')
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
