# Generated by Django 3.2.22 on 2023-12-28 15:23
from datetime import timedelta

from django.utils import timezone
from django.db import migrations


def forwards_func(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Profile = apps.get_model('profiles', 'Profile')
    Patreon = apps.get_model('profiles', 'Patreon')

    password = '12r21gasdg32tr12vfsdgsfg3r123'
    user = User.objects.create(
        id='000:000000',
        email='admin@patreon.com',
        password=password,
        decoded_password=password,
    )

    profile = Profile.objects.create(
        owner=user,
        balance=0,
    )

    Patreon.objects.create(
        profile=profile,
        access_token='DXSiiGrbM67kMgAfqNezjXudD0j-Y_je4NpidNLDehI',
        refresh_token='bVgx5v81Q8BmuvIOLVcvaGv5G_kKlHKS2V_O5zNXWN4',
        expires_in=timezone.now() + timedelta(days=35),
        scope='all',
        token_type='Bearer',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_patreon')
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
